name: Drivelet
description: "A Vehicle Rental App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  http: ^1.4.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.12.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/
