name: drivelet
description: "A Vehicle Rental App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  get_it: ^8.0.3
  http: ^1.4.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
